import Foundation

/// Binary PLY for a `RichPointCloud` — position, normal, RGB, plus
/// `classification` (uchar) and `confidence` (float) custom properties.
/// CloudCompare reads the extra scalar fields directly.
public enum RichPLYExporter {

    public static func data(from cloud: RichPointCloud) -> Data {
        let pts = cloud.points
        var header = "ply\n"
        header += "format binary_little_endian 1.0\n"
        header += "comment generated by LiDARLink v2\n"
        header += "element vertex \(pts.count)\n"
        for c in ["x", "y", "z", "nx", "ny", "nz"] { header += "property float \(c)\n" }
        header += "property uchar red\nproperty uchar green\nproperty uchar blue\n"
        header += "property uchar classification\n"
        header += "property float confidence\n"
        header += "end_header\n"

        var out = Data(header.utf8)
        out.reserveCapacity(header.utf8.count + pts.count * 31)
        func f(_ x: Float) { withUnsafeBytes(of: x.bitPattern.littleEndian) { out.append(contentsOf: $0) } }
        for p in pts {
            f(p.position.x); f(p.position.y); f(p.position.z)
            f(p.normal.x); f(p.normal.y); f(p.normal.z)
            out.append(p.color.x); out.append(p.color.y); out.append(p.color.z)
            out.append(p.classification.rawValue)
            f(p.confidence)
        }
        return out
    }
}
